import React, { useState, useEffect } from 'react';
import { 
  User, 
  FileText, 
  Bell, 
  CreditCard, 
  Shield, 
  Save, 
  Upload, 
  CheckCircle2,
  AlertCircle,
  LogOut,
  ChevronRight
} from 'lucide-react';
import { useFirebase } from '../components/FirebaseProvider';
import { useInvoiceLimit } from '../hooks/useInvoiceLimit';
import { usePricing } from '../components/PricingContext';
import { db, doc, updateDoc, OperationType, handleFirestoreError } from '../firebase';
import { motion, AnimatePresence } from 'motion/react';
import { INDIAN_STATES } from '../lib/gst-calculator';
import { clsx, type ClassValue } from 'clsx';
import { twMerge } from 'tailwind-merge';
import AdminPanel from './AdminPanel';

function cn(...inputs: ClassValue[]) {
  return twMerge(clsx(inputs));
}

const SettingsPage = () => {
  const { profile } = useFirebase();
  const { invoiceCount, limit, remaining } = useInvoiceLimit();
  const { openPricing } = usePricing();
  const [activeTab, setActiveTab] = useState<'profile' | 'invoice' | 'notifications' | 'billing' | 'security' | 'admin'>('profile');
  const isAdmin = profile?.role === 'admin' || profile?.email === 'mshijacknew@gmail.com';
  const [isSaving, setIsSaving] = useState(false);
  const [saveSuccess, setSaveSuccess] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const [formData, setFormData] = useState({
    businessName: '',
    shopName: '',
    displayName: '',
    email: '',
    phone: '',
    gstin: '',
    address: '',
    state: 'Rajasthan',
    bankDetails: {
      bankName: '',
      accountNumber: '',
      ifsc: '',
      upiId: ''
    },
    invoiceSettings: {
      prefix: 'INV',
      startingNumber: 1,
      defaultGstRate: 18,
      paymentTerms: 'Immediate',
      defaultNotes: 'Thank you for your business! GST invoice generated by BillAI.',
      autoGenerateNumber: true,
      sendEmailCopy: true,
      showBankDetails: true,
      enableSignature: false,
      themeColor: '#f97316',
      logoUrl: '',
      signatureUrl: '',
      fontStyle: 'sans',
      templateStyle: 'modern'
    },
    notifications: {
      emailAlerts: true,
      whatsappAlerts: true,
      paymentReminders: true,
      monthlyReports: true
    }
  });

  useEffect(() => {
    if (profile) {
      setFormData({
        businessName: profile.businessName || '',
        shopName: profile.shopName || '',
        displayName: profile.displayName || '',
        email: profile.email || '',
        phone: profile.phone || '',
        gstin: profile.gstin || '',
        address: profile.address || '',
        state: profile.state || 'Rajasthan',
        bankDetails: {
          bankName: profile.bankDetails?.bankName || '',
          accountNumber: profile.bankDetails?.accountNumber || '',
          ifsc: profile.bankDetails?.ifsc || '',
          upiId: profile.bankDetails?.upiId || ''
        },
        invoiceSettings: {
          prefix: profile.invoiceSettings?.prefix || 'INV',
          startingNumber: profile.invoiceSettings?.startingNumber || 1,
          defaultGstRate: profile.invoiceSettings?.defaultGstRate || 18,
          paymentTerms: profile.invoiceSettings?.paymentTerms || 'Immediate',
          defaultNotes: profile.invoiceSettings?.defaultNotes || 'Thank you for your business! GST invoice generated by BillAI.',
          autoGenerateNumber: profile.invoiceSettings?.autoGenerateNumber ?? true,
          sendEmailCopy: profile.invoiceSettings?.sendEmailCopy ?? true,
          showBankDetails: profile.invoiceSettings?.showBankDetails ?? true,
          enableSignature: profile.invoiceSettings?.enableSignature ?? false,
          themeColor: profile.invoiceSettings?.themeColor || '#f97316',
          logoUrl: profile.invoiceSettings?.logoUrl || '',
          signatureUrl: profile.invoiceSettings?.signatureUrl || '',
          fontStyle: profile.invoiceSettings?.fontStyle || 'sans',
          templateStyle: profile.invoiceSettings?.templateStyle || 'modern'
        },
        notifications: {
          emailAlerts: profile.notifications?.emailAlerts ?? true,
          whatsappAlerts: profile.notifications?.whatsappAlerts ?? true,
          paymentReminders: profile.notifications?.paymentReminders ?? true,
          monthlyReports: profile.notifications?.monthlyReports ?? true
        }
      });
    }
  }, [profile]);

  const handleSave = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!profile) {
      setError('Profile load nahi hua hai. Please wait or refresh.');
      return;
    }
    setIsSaving(true);
    setError(null);
    try {
      // Recursive function to clean object of undefined values
      const cleanData = (obj: any): any => {
        const cleaned: any = Array.isArray(obj) ? [] : {};
        Object.keys(obj).forEach(key => {
          const value = obj[key];
          if (value !== undefined && value !== null) {
            if (typeof value === 'object' && !Array.isArray(value) && !(value instanceof Date)) {
              cleaned[key] = cleanData(value);
            } else {
              cleaned[key] = value;
            }
          }
        });
        return cleaned;
      };

      const updateData = cleanData(formData);
      
      // Ensure we don't accidentally try to update plan or role if they were somehow in formData
      delete updateData.plan;
      delete updateData.role;
      delete updateData.uid;
      delete updateData.createdAt;

      await updateDoc(doc(db, 'users', profile.uid), updateData);
      setSaveSuccess(true);
      setTimeout(() => setSaveSuccess(false), 3000);
    } catch (err: any) {
      console.error('Save Error:', err);
      let errorMessage = 'Settings save karne mein error aayi.';
      
      // Try to extract a more meaningful error message
      const errorStr = err instanceof Error ? err.message : String(err);
      if (errorStr.includes('permission-denied')) {
        errorMessage = 'Permission denied. Aapko is profile ko update karne ka haq nahi hai.';
      } else {
        try {
          const parsed = JSON.parse(errorStr);
          if (parsed.error) errorMessage = `Error: ${parsed.error}`;
        } catch (e) {
          errorMessage = `Error: ${errorStr}`;
        }
      }
      
      setError(errorMessage);
      handleFirestoreError(err, OperationType.UPDATE, `users/${profile.uid}`);
    } finally {
      setIsSaving(false);
    }
  };

  const tabs = [
    { id: 'profile', label: 'Business Profile', icon: User },
    { id: 'invoice', label: 'Invoice Settings', icon: FileText },
    { id: 'notifications', label: 'Notifications', icon: Bell },
    { id: 'billing', label: 'Billing & Usage', icon: CreditCard },
    { id: 'security', label: 'Security', icon: Shield },
    ...(isAdmin ? [{ id: 'admin', label: 'Admin Panel', icon: Shield }] : []),
  ];

  return (
    <div className="flex flex-col lg:flex-row gap-6 lg:gap-8">
      {/* Sub-nav */}
      <aside className="lg:w-64 flex lg:flex-col gap-2 overflow-x-auto lg:overflow-x-visible no-scrollbar pb-2 lg:pb-0 -mx-4 px-4 lg:mx-0 lg:px-0">
        {tabs.map((tab) => (
          <button
            key={tab.id}
            onClick={() => setActiveTab(tab.id as any)}
            className={cn(
              "flex-shrink-0 lg:w-full flex items-center justify-between px-4 py-3 rounded-xl transition-all duration-200 group whitespace-nowrap",
              activeTab === tab.id 
                ? "bg-orange-500/10 text-orange-500 border border-orange-500/20" 
                : "text-gray-400 hover:bg-white/5 hover:text-white border border-transparent"
            )}
          >
            <div className="flex items-center gap-3">
              <tab.icon className={cn("w-5 h-5", activeTab === tab.id ? "text-orange-500" : "text-gray-400 group-hover:text-white")} />
              <span className="font-medium text-sm">{tab.label}</span>
            </div>
            <ChevronRight className={cn("hidden lg:block w-4 h-4 transition-transform", activeTab === tab.id ? "rotate-90" : "")} />
          </button>
        ))}
      </aside>

      {/* Content Area */}
      <div className="flex-1 min-w-0">
        <AnimatePresence mode="wait">
          {activeTab === 'profile' && (
            <motion.div
              key="profile"
              initial={{ opacity: 0, y: 10 }}
              animate={{ opacity: 1, y: 0 }}
              exit={{ opacity: 0, y: -10 }}
              className="glass p-5 md:p-8 rounded-[2rem] md:rounded-[2.5rem] border border-white/5"
            >
              <div className="flex flex-col md:flex-row md:items-center justify-between gap-4 mb-8 md:mb-10">
                <div>
                  <h2 className="text-xl md:text-2xl font-bold">Business Profile</h2>
                  <p className="text-sm text-gray-500">Apne business ki details update karo</p>
                </div>
                {saveSuccess && (
                  <div className="flex items-center gap-2 text-green-500 text-sm font-bold bg-green-500/10 px-4 py-2 rounded-full border border-green-500/20 self-start">
                    <CheckCircle2 className="w-4 h-4" /> Business Profile save ho gayi!
                  </div>
                )}
                {error && (
                  <div className="flex items-center gap-2 text-red-500 text-sm font-bold bg-red-500/10 px-4 py-2 rounded-full border border-red-500/20 self-start">
                    <AlertCircle className="w-4 h-4" /> {error}
                  </div>
                )}
              </div>

              <form onSubmit={handleSave} className="space-y-8">
                <div className="flex items-center gap-6 mb-10">
                  <div 
                    onClick={() => document.getElementById('logo-upload')?.click()}
                    className="w-24 h-24 rounded-[2rem] bg-orange-500/10 border-2 border-dashed border-orange-500/30 flex flex-col items-center justify-center text-orange-500 cursor-pointer hover:bg-orange-500/20 transition-all group overflow-hidden"
                  >
                    {formData.invoiceSettings.logoUrl ? (
                      <img 
                        src={formData.invoiceSettings.logoUrl} 
                        alt="Logo" 
                        className="w-full h-full object-contain p-2"
                        referrerPolicy="no-referrer"
                      />
                    ) : (
                      <>
                        <Upload className="w-6 h-6 mb-1 group-hover:scale-110 transition-transform" />
                        <span className="text-[10px] font-bold uppercase tracking-widest">Logo</span>
                      </>
                    )}
                    <input 
                      id="logo-upload"
                      type="file" 
                      accept="image/*"
                      className="hidden"
                      onChange={(e) => {
                        const file = e.target.files?.[0];
                        if (file) {
                          if (file.size > 2 * 1024 * 1024) {
                            setError('Logo size 2MB se kam honi chaiye');
                            return;
                          }
                          const reader = new FileReader();
                          reader.onloadend = () => {
                            setFormData({
                              ...formData,
                              invoiceSettings: {
                                ...formData.invoiceSettings,
                                logoUrl: reader.result as string
                              }
                            });
                          };
                          reader.readAsDataURL(file);
                        }
                      }}
                    />
                  </div>
                  <div>
                    <h4 className="font-bold mb-1">Business Logo</h4>
                    <p className="text-xs text-gray-500">PNG or JPG. Max 2MB.</p>
                    {formData.invoiceSettings.logoUrl && (
                      <button 
                        type="button"
                        onClick={() => setFormData({
                          ...formData,
                          invoiceSettings: { ...formData.invoiceSettings, logoUrl: '' }
                        })}
                        className="text-[10px] text-red-500 font-bold uppercase tracking-widest mt-2 hover:underline"
                      >
                        Remove Logo
                      </button>
                    )}
                  </div>
                </div>

                <div className="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-3 gap-6 sm:gap-8">
                  <div className="space-y-1">
                    <label className="text-xs font-bold text-gray-500 uppercase tracking-wider ml-1">Business Name *</label>
                    <input 
                      required
                      type="text" 
                      value={formData.businessName}
                      onChange={(e) => setFormData({...formData, businessName: e.target.value})}
                      placeholder="Gupta Shoes" 
                      className="input-dark w-full" 
                    />
                  </div>
                  <div className="space-y-1">
                    <label className="text-xs font-bold text-gray-500 uppercase tracking-wider ml-1">Shop Name (Optional)</label>
                    <input 
                      type="text" 
                      value={formData.shopName}
                      onChange={(e) => setFormData({...formData, shopName: e.target.value})}
                      placeholder="Gupta Shoes & Co." 
                      className="input-dark w-full" 
                    />
                  </div>
                  <div className="space-y-1">
                    <label className="text-xs font-bold text-gray-500 uppercase tracking-wider ml-1">Owner Name *</label>
                    <input 
                      required
                      type="text" 
                      value={formData.displayName}
                      onChange={(e) => setFormData({...formData, displayName: e.target.value})}
                      placeholder="Ramesh Gupta" 
                      className="input-dark w-full" 
                    />
                  </div>
                  <div className="space-y-1">
                    <label className="text-xs font-bold text-gray-500 uppercase tracking-wider ml-1">Email *</label>
                    <input 
                      required
                      type="email" 
                      value={formData.email}
                      onChange={(e) => setFormData({...formData, email: e.target.value})}
                      placeholder="ramesh@company.com" 
                      className="input-dark w-full" 
                    />
                  </div>
                  <div className="space-y-1">
                    <label className="text-xs font-bold text-gray-500 uppercase tracking-wider ml-1">Phone *</label>
                    <input 
                      required
                      type="tel" 
                      value={formData.phone}
                      onChange={(e) => setFormData({...formData, phone: e.target.value})}
                      placeholder="9876543210" 
                      className="input-dark w-full" 
                    />
                  </div>
                  <div className="space-y-1">
                    <label className="text-xs font-bold text-gray-500 uppercase tracking-wider ml-1">GSTIN</label>
                    <input 
                      type="text" 
                      value={formData.gstin}
                      onChange={(e) => setFormData({...formData, gstin: e.target.value})}
                      placeholder="08ABCDE1234F1Z5" 
                      className="input-dark w-full" 
                    />
                  </div>
                  <div className="space-y-1">
                    <label className="text-xs font-bold text-gray-500 uppercase tracking-wider ml-1">State</label>
                    <select 
                      value={formData.state}
                      onChange={(e) => setFormData({...formData, state: e.target.value})}
                      className="input-dark w-full appearance-none"
                    >
                      {INDIAN_STATES.map(s => <option key={s} value={s}>{s}</option>)}
                    </select>
                  </div>
                </div>

                <div className="space-y-1">
                  <label className="text-xs font-bold text-gray-500 uppercase tracking-wider ml-1">Address</label>
                  <textarea 
                    value={formData.address}
                    onChange={(e) => setFormData({...formData, address: e.target.value})}
                    placeholder="Full business address..." 
                    className="input-dark w-full h-24 resize-none" 
                  />
                </div>

                <div className="pt-8 border-t border-white/5">
                  <h3 className="text-lg font-bold mb-6">Bank Details</h3>
                  <div className="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-4 gap-6 sm:gap-8">
                    <div className="space-y-1">
                      <label className="text-xs font-bold text-gray-500 uppercase tracking-wider ml-1">Bank Name</label>
                      <input 
                        type="text" 
                        value={formData.bankDetails.bankName}
                        onChange={(e) => setFormData({...formData, bankDetails: {...formData.bankDetails, bankName: e.target.value}})}
                        placeholder="State Bank of India" 
                        className="input-dark w-full" 
                      />
                    </div>
                    <div className="space-y-1">
                      <label className="text-xs font-bold text-gray-500 uppercase tracking-wider ml-1">Account Number</label>
                      <input 
                        type="text" 
                        value={formData.bankDetails.accountNumber}
                        onChange={(e) => setFormData({...formData, bankDetails: {...formData.bankDetails, accountNumber: e.target.value}})}
                        placeholder="XXXX XXXX 1234" 
                        className="input-dark w-full" 
                      />
                    </div>
                    <div className="space-y-1">
                      <label className="text-xs font-bold text-gray-500 uppercase tracking-wider ml-1">IFSC Code</label>
                      <input 
                        type="text" 
                        value={formData.bankDetails.ifsc}
                        onChange={(e) => setFormData({...formData, bankDetails: {...formData.bankDetails, ifsc: e.target.value}})}
                        placeholder="SBIN0001234" 
                        className="input-dark w-full" 
                      />
                    </div>
                    <div className="space-y-1">
                      <label className="text-xs font-bold text-gray-500 uppercase tracking-wider ml-1">UPI ID</label>
                      <input 
                        type="text" 
                        value={formData.bankDetails.upiId}
                        onChange={(e) => setFormData({...formData, bankDetails: {...formData.bankDetails, upiId: e.target.value}})}
                        placeholder="billai@upi" 
                        className="input-dark w-full" 
                      />
                    </div>
                  </div>
                </div>

                <div className="flex justify-end pt-8">
                  <button type="submit" disabled={isSaving} className="btn-orange flex items-center gap-2">
                    {isSaving ? <span className="w-5 h-5 border-2 border-white/30 border-t-white rounded-full animate-spin" /> : <Save className="w-5 h-5" />}
                    Changes Save karo
                  </button>
                </div>
              </form>
            </motion.div>
          )}

          {activeTab === 'notifications' && (
            <motion.div
              key="notifications"
              initial={{ opacity: 0, y: 10 }}
              animate={{ opacity: 1, y: 0 }}
              exit={{ opacity: 0, y: -10 }}
              className="glass p-5 md:p-8 rounded-[2rem] md:rounded-[2.5rem] border border-white/5"
            >
              <div className="flex flex-col md:flex-row md:items-center justify-between gap-4 mb-8 md:mb-10">
                <div>
                  <h2 className="text-xl md:text-2xl font-bold">Notifications</h2>
                  <p className="text-sm text-gray-500">Apne alerts manage karo</p>
                </div>
                {saveSuccess && (
                  <div className="flex items-center gap-2 text-green-500 text-sm font-bold bg-green-500/10 px-4 py-2 rounded-full border border-green-500/20 self-start">
                    <CheckCircle2 className="w-4 h-4" /> Notifications save ho gayi!
                  </div>
                )}
                {error && (
                  <div className="flex items-center gap-2 text-red-500 text-sm font-bold bg-red-500/10 px-4 py-2 rounded-full border border-red-500/20 self-start">
                    <AlertCircle className="w-4 h-4" /> {error}
                  </div>
                )}
              </div>

              <form onSubmit={handleSave} className="space-y-6">
                {[
                  { key: 'emailAlerts', label: 'Email Alerts', desc: 'Naye invoice aur payments ki email updates' },
                  { key: 'whatsappAlerts', label: 'WhatsApp Alerts', desc: 'Direct WhatsApp par notifications' },
                  { key: 'paymentReminders', label: 'Payment Reminders', desc: 'Overdue invoices ke auto-reminders' },
                  { key: 'monthlyReports', label: 'Monthly Reports', desc: 'Har mahine ki summary report' }
                ].map(n => (
                  <div key={n.key} className="flex items-center justify-between p-6 bg-white/5 rounded-[2rem] border border-white/5">
                    <div>
                      <p className="font-bold">{n.label}</p>
                      <p className="text-xs text-gray-500">{n.desc}</p>
                    </div>
                    <div 
                      onClick={() => setFormData({
                        ...formData, 
                        notifications: {
                          ...formData.notifications, 
                          [n.key]: !formData.notifications[n.key as keyof typeof formData.notifications]
                        }
                      })}
                      className={cn(
                        "w-12 h-6 rounded-full relative transition-colors cursor-pointer",
                        formData.notifications[n.key as keyof typeof formData.notifications] ? "bg-orange-500" : "bg-white/10"
                      )}
                    >
                      <div className={cn(
                        "absolute top-1 w-4 h-4 bg-white rounded-full transition-all",
                        formData.notifications[n.key as keyof typeof formData.notifications] ? "right-1" : "left-1"
                      )} />
                    </div>
                  </div>
                ))}

                <div className="flex justify-end pt-8">
                  <button type="submit" disabled={isSaving} className="btn-orange flex items-center gap-2">
                    {isSaving ? <span className="w-5 h-5 border-2 border-white/30 border-t-white rounded-full animate-spin" /> : <Save className="w-5 h-5" />}
                    Changes Save karo
                  </button>
                </div>
              </form>
            </motion.div>
          )}

          {activeTab === 'billing' && (
            <motion.div
              key="billing"
              initial={{ opacity: 0, y: 10 }}
              animate={{ opacity: 1, y: 0 }}
              exit={{ opacity: 0, y: -10 }}
              className="space-y-6 md:space-y-8"
            >
              <div className="glass p-6 md:p-10 rounded-[2rem] md:rounded-[2.5rem] border border-white/5 flex flex-col md:flex-row justify-between items-center gap-6 md:gap-8">
                <div className="text-center md:text-left">
                  <div className="bg-orange-500/10 text-orange-500 text-[10px] font-bold px-3 py-1 rounded-full uppercase tracking-widest inline-block mb-4">Current Plan</div>
                  <h2 className="text-3xl md:text-4xl font-display font-bold mb-2">{profile?.plan === 'pro' ? 'PRO PLAN' : 'FREE PLAN'}</h2>
                  <p className="text-gray-400">
                    {profile?.plan === 'pro' 
                      ? `Unlimited invoices until ${profile.planExpiry ? new Date(profile.planExpiry).toLocaleDateString() : 'next month'}` 
                      : '20 invoices per month'}
                  </p>
                </div>
                <div className="flex-1 max-w-xs w-full">
                  <div className="flex justify-between text-xs font-bold mb-2">
                    <span className="text-gray-500 uppercase tracking-widest">Usage</span>
                    <span className="text-orange-500">{invoiceCount}/{limit} used</span>
                  </div>
                  <div className="h-2 bg-white/5 rounded-full overflow-hidden">
                    <div 
                      className={cn(
                        "h-full transition-all duration-500",
                        invoiceCount >= limit ? "bg-red-500" : "bg-orange-500"
                      )} 
                      style={{ width: `${Math.min(100, (invoiceCount / limit) * 100)}%` }} 
                    />
                  </div>
                  <p className="text-[10px] text-gray-600 mt-2 text-right">
                    {remaining > 0 
                      ? `Is mahine ${remaining} invoices bache hain` 
                      : "Aapki is mahine ki limit khatam ho gayi hai"}
                  </p>
                </div>
              </div>

              <div className="glass p-6 md:p-10 rounded-[2rem] md:rounded-[2.5rem] border-2 border-orange-500 relative overflow-hidden">
                <div className="absolute top-0 right-0 w-64 h-64 bg-orange-500/10 rounded-full blur-[100px] -mr-32 -mt-32" />
                <div className="relative z-10">
                  <h3 className="text-2xl font-bold mb-2">Upgrade to PRO</h3>
                  <p className="text-gray-400 mb-8 max-w-md">Get unlimited invoices, GST reports, PDF exports, and priority support.</p>
                  
                  <div className="grid grid-cols-1 sm:grid-cols-2 gap-4 mb-10">
                    {[
                      'Unlimited invoices',
                      'GST reports + export',
                      'WhatsApp sharing',
                      'Priority support',
                      'Custom invoice branding',
                      'Multi-user access'
                    ].map(f => (
                      <div key={f} className="flex items-center gap-3 text-sm text-gray-300">
                        <CheckCircle2 className="w-5 h-5 text-orange-500" /> {f}
                      </div>
                    ))}
                  </div>

                  <div className="flex flex-col sm:flex-row items-center gap-6">
                    <div className="text-center sm:text-left">
                      <div className="flex items-center gap-2 mb-1">
                        <span className="text-lg text-gray-500 line-through">₹199</span>
                        <p className="text-4xl font-display font-bold">₹99 <span className="text-lg text-gray-500 font-normal">/month</span></p>
                      </div>
                      <p className="text-[10px] text-gray-600 uppercase tracking-widest font-bold">Priority Support Included</p>
                    </div>
                    <button onClick={openPricing} className="btn-orange px-10">Pro upgrade karo →</button>
                  </div>
                </div>
              </div>
            </motion.div>
          )}

          {activeTab === 'invoice' && (
            <motion.div
              key="invoice"
              initial={{ opacity: 0, y: 10 }}
              animate={{ opacity: 1, y: 0 }}
              exit={{ opacity: 0, y: -10 }}
              className="glass p-5 md:p-8 rounded-[2rem] md:rounded-[2.5rem] border border-white/5"
            >
              <div className="flex flex-col md:flex-row md:items-center justify-between gap-4 mb-8 md:mb-10">
                <div>
                  <h2 className="text-xl md:text-2xl font-bold">Invoice Settings</h2>
                  <p className="text-sm text-gray-500">Invoices ko customize karo</p>
                </div>
                {saveSuccess && (
                  <div className="flex items-center gap-2 text-green-500 text-sm font-bold bg-green-500/10 px-4 py-2 rounded-full border border-green-500/20 self-start">
                    <CheckCircle2 className="w-4 h-4" /> Invoice Settings save ho gayi!
                  </div>
                )}
                {error && (
                  <div className="flex items-center gap-2 text-red-500 text-sm font-bold bg-red-500/10 px-4 py-2 rounded-full border border-red-500/20 self-start">
                    <AlertCircle className="w-4 h-4" /> {error}
                  </div>
                )}
              </div>

              <form onSubmit={handleSave} className="space-y-8">
                <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                  <div className="space-y-1">
                    <label className="text-xs font-bold text-gray-500 uppercase tracking-wider ml-1">Invoice Prefix</label>
                    <input 
                      type="text" 
                      value={formData.invoiceSettings.prefix}
                      onChange={(e) => setFormData({...formData, invoiceSettings: {...formData.invoiceSettings, prefix: e.target.value}})}
                      className="input-dark w-full" 
                    />
                    <p className="text-[10px] text-gray-600 ml-1">Preview: {formData.invoiceSettings.prefix}-0001</p>
                  </div>
                  <div className="space-y-1">
                    <label className="text-xs font-bold text-gray-500 uppercase tracking-wider ml-1">Starting Number</label>
                    <input 
                      type="number" 
                      value={formData.invoiceSettings.startingNumber}
                      onChange={(e) => setFormData({...formData, invoiceSettings: {...formData.invoiceSettings, startingNumber: parseInt(e.target.value) || 1}})}
                      className="input-dark w-full" 
                    />
                  </div>
                  <div className="space-y-1">
                    <label className="text-xs font-bold text-gray-500 uppercase tracking-wider ml-1">Default GST Rate (%)</label>
                    <select 
                      value={formData.invoiceSettings.defaultGstRate}
                      onChange={(e) => setFormData({...formData, invoiceSettings: {...formData.invoiceSettings, defaultGstRate: parseInt(e.target.value)}})}
                      className="input-dark w-full appearance-none"
                    >
                      {[0, 5, 12, 18, 28].map(rate => <option key={rate} value={rate}>{rate}%</option>)}
                    </select>
                  </div>
                  <div className="space-y-1">
                    <label className="text-xs font-bold text-gray-500 uppercase tracking-wider ml-1">Payment Terms</label>
                    <select 
                      value={formData.invoiceSettings.paymentTerms}
                      onChange={(e) => setFormData({...formData, invoiceSettings: {...formData.invoiceSettings, paymentTerms: e.target.value}})}
                      className="input-dark w-full appearance-none"
                    >
                      <option>Immediate</option>
                      <option>7 days</option>
                      <option>15 days</option>
                      <option>30 days</option>
                    </select>
                  </div>
                  <div className="space-y-1">
                    <label className="text-xs font-bold text-gray-500 uppercase tracking-wider ml-1">Invoice Theme Color</label>
                    <div className="flex items-center gap-4">
                      <input 
                        type="color" 
                        value={formData.invoiceSettings.themeColor}
                        onChange={(e) => setFormData({...formData, invoiceSettings: {...formData.invoiceSettings, themeColor: e.target.value}})}
                        className="w-12 h-12 rounded-xl bg-white/5 border border-white/10 cursor-pointer p-1" 
                      />
                      <div className="flex-1">
                        <input 
                          type="text" 
                          value={formData.invoiceSettings.themeColor}
                          onChange={(e) => setFormData({...formData, invoiceSettings: {...formData.invoiceSettings, themeColor: e.target.value}})}
                          className="input-dark w-full font-mono uppercase" 
                        />
                      </div>
                    </div>
                  </div>
                  <div className="space-y-1">
                    <label className="text-xs font-bold text-gray-500 uppercase tracking-wider ml-1">Logo URL (Optional)</label>
                    <div className="flex gap-4">
                      <div className="flex-1">
                        <input 
                          type="text" 
                          value={formData.invoiceSettings.logoUrl}
                          onChange={(e) => setFormData({...formData, invoiceSettings: {...formData.invoiceSettings, logoUrl: e.target.value}})}
                          placeholder="https://example.com/logo.png"
                          className="input-dark w-full" 
                        />
                      </div>
                      {formData.invoiceSettings.logoUrl && (
                        <div className="w-12 h-12 rounded-xl bg-white/5 border border-white/10 p-1 flex items-center justify-center overflow-hidden">
                          <img 
                            src={formData.invoiceSettings.logoUrl} 
                            alt="Logo Preview" 
                            className="max-w-full max-h-full object-contain"
                            referrerPolicy="no-referrer"
                          />
                        </div>
                      )}
                    </div>
                  </div>
                  <div className="space-y-1">
                    <label className="text-xs font-bold text-gray-500 uppercase tracking-wider ml-1">Signature URL (Optional)</label>
                    <div className="flex gap-4">
                      <div className="flex-1">
                        <input 
                          type="text" 
                          value={formData.invoiceSettings.signatureUrl}
                          onChange={(e) => setFormData({...formData, invoiceSettings: {...formData.invoiceSettings, signatureUrl: e.target.value}})}
                          placeholder="https://example.com/signature.png"
                          className="input-dark w-full" 
                        />
                      </div>
                      {formData.invoiceSettings.signatureUrl && (
                        <div className="w-12 h-12 rounded-xl bg-white/5 border border-white/10 p-1 flex items-center justify-center overflow-hidden">
                          <img 
                            src={formData.invoiceSettings.signatureUrl} 
                            alt="Signature Preview" 
                            className="max-w-full max-h-full object-contain invert"
                            referrerPolicy="no-referrer"
                          />
                        </div>
                      )}
                    </div>
                  </div>
                  <div className="space-y-1">
                    <label className="text-xs font-bold text-gray-500 uppercase tracking-wider ml-1">Font Style</label>
                    <select 
                      value={formData.invoiceSettings.fontStyle}
                      onChange={(e) => setFormData({...formData, invoiceSettings: {...formData.invoiceSettings, fontStyle: e.target.value as any}})}
                      className="input-dark w-full appearance-none"
                    >
                      <option value="sans">Modern Sans (Clean)</option>
                      <option value="serif">Elegant Serif (Professional)</option>
                      <option value="mono">Technical Mono (Modern)</option>
                    </select>
                  </div>
                  <div className="space-y-1">
                    <label className="text-xs font-bold text-gray-500 uppercase tracking-wider ml-1">Template Style</label>
                    <select 
                      value={formData.invoiceSettings.templateStyle}
                      onChange={(e) => setFormData({...formData, invoiceSettings: {...formData.invoiceSettings, templateStyle: e.target.value as any}})}
                      className="input-dark w-full appearance-none"
                    >
                      <option value="modern">Modern (Recommended)</option>
                      <option value="professional">Professional (Corporate)</option>
                      <option value="classic">Classic (Standard)</option>
                      <option value="minimal">Minimal (Clean)</option>
                    </select>
                  </div>
                </div>

                <div className="space-y-1">
                  <label className="text-xs font-bold text-gray-500 uppercase tracking-wider ml-1">Default Invoice Notes</label>
                  <textarea 
                    value={formData.invoiceSettings.defaultNotes}
                    onChange={(e) => setFormData({...formData, invoiceSettings: {...formData.invoiceSettings, defaultNotes: e.target.value}})}
                    className="input-dark w-full h-24 resize-none" 
                  />
                </div>

                <div className="space-y-4 pt-6">
                  {[
                    { key: 'autoGenerateNumber', label: 'Auto-generate invoice number' },
                    { key: 'sendEmailCopy', label: 'Send invoice copy to my email' },
                    { key: 'showBankDetails', label: 'Show bank details on invoice' },
                    { key: 'enableSignature', label: 'Enable digital signature' }
                  ].map(t => (
                    <div key={t.key} className="flex items-center justify-between p-4 bg-white/5 rounded-2xl border border-white/5">
                      <span className="text-sm font-medium">{t.label}</span>
                      <div 
                        onClick={() => setFormData({
                          ...formData, 
                          invoiceSettings: {
                            ...formData.invoiceSettings, 
                            [t.key]: !formData.invoiceSettings[t.key as keyof typeof formData.invoiceSettings]
                          }
                        })}
                        className={cn(
                          "w-12 h-6 rounded-full relative transition-colors cursor-pointer",
                          formData.invoiceSettings[t.key as keyof typeof formData.invoiceSettings] ? "bg-orange-500" : "bg-white/10"
                        )}
                      >
                        <div className={cn(
                          "absolute top-1 w-4 h-4 bg-white rounded-full transition-all",
                          formData.invoiceSettings[t.key as keyof typeof formData.invoiceSettings] ? "right-1" : "left-1"
                        )} />
                      </div>
                    </div>
                  ))}
                </div>

                <div className="flex justify-end pt-8">
                  <button type="submit" disabled={isSaving} className="btn-orange flex items-center gap-2">
                    {isSaving ? <span className="w-5 h-5 border-2 border-white/30 border-t-white rounded-full animate-spin" /> : <Save className="w-5 h-5" />}
                    Changes Save karo
                  </button>
                </div>
              </form>
            </motion.div>
          )}



          {activeTab === 'admin' && isAdmin && (
            <motion.div
              key="admin"
              initial={{ opacity: 0, y: 10 }}
              animate={{ opacity: 1, y: 0 }}
              exit={{ opacity: 0, y: -10 }}
            >
              <AdminPanel />
            </motion.div>
          )}

          {activeTab === 'security' && (
            <motion.div
              key="security"
              initial={{ opacity: 0, y: 10 }}
              animate={{ opacity: 1, y: 0 }}
              exit={{ opacity: 0, y: -10 }}
              className="space-y-6 md:space-y-8"
            >
              <div className="glass p-5 md:p-8 rounded-[2rem] md:rounded-[2.5rem] border border-white/5">
                <h2 className="text-xl md:text-2xl font-bold mb-2">Security</h2>
                <p className="text-sm text-gray-500 mb-8 md:mb-10">Manage your account security</p>

                <div className="space-y-6">
                  <div className="flex items-center justify-between p-6 bg-white/5 rounded-2xl border border-white/5">
                    <div className="flex items-center gap-4">
                      <div className="w-12 h-12 bg-orange-500/10 rounded-xl flex items-center justify-center">
                        <Shield className="w-6 h-6 text-orange-500" />
                      </div>
                      <div>
                        <p className="font-bold">Two-Factor Authentication</p>
                        <p className="text-xs text-gray-500">Add an extra layer of security</p>
                      </div>
                    </div>
                    <button className="px-4 py-2 border border-white/10 rounded-xl text-xs font-bold hover:bg-white/5">Enable</button>
                  </div>

                  <div className="p-6 bg-red-500/5 rounded-2xl border border-red-500/10">
                    <h4 className="text-red-500 font-bold mb-2 flex items-center gap-2">
                      <AlertCircle className="w-4 h-4" /> Danger Zone
                    </h4>
                    <p className="text-xs text-gray-500 mb-6">Once you delete your account, there is no going back. Please be certain.</p>
                    <button className="px-6 py-3 bg-red-500/10 hover:bg-red-500/20 text-red-500 rounded-xl text-sm font-bold transition-all">
                      Delete Account
                    </button>
                  </div>
                </div>
              </div>
            </motion.div>
          )}
        </AnimatePresence>
      </div>
    </div>
  );
};

export default SettingsPage;
